
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT}:8000"
    expose:
      - "${PORT}"
    env_file:
      - .env
    command: >
      bash -c "mkdir -p /app/Database &&
      cd /app && PYTHONPATH=/app python /app/src/database.py &&
      uvicorn src.app:app --host 0.0.0.0 --port ${PORT} --reload"
    develop:
      watch:
        - action: rebuild
          path: Dockerfile
        - action: rebuild
          path: requirements.txt
        - action: rebuild
          path: compose.yaml
        - action: rebuild
          path: src/app.py
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${PORT}/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: unless-stopped

networks:
  default:
    driver: bridge